apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpressrs1

spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      app: wp
  template:
    metadata:
      name: wordpresspod1
      labels:
        env: dev
        app: wp
    spec:
      containers:
      - name: "wordpresscon1"
        image: "wordpress:4.8-apache"


